### ISSUE TITLE
Layout flows from left to right

### ISSUE THREAD

**Issue by awnawnawn** [Spope/MiniMasonry.js#6]
When the number of elements is not enough to wrap, it will be displayed in the middle, which should be from left to right

**Comment by Spope** [comment]
Indeed, 5px is the default value of the "ultimateGutter" parameter. It is the gutter size when only one column fits into the container.
You can find it into the documentation, but I agree those gutters would need some improvement to be more comprehensible.

**Comment by awnawnawn** [comment]
Oh! I understand the usage of this parameter, thank you for your answer!
I still have some questions for you
1. If my wrap width is `1200px` and `baseWidth` is set to `300`, then there will be `4 columns`. But when I have only `3 elements`, the flow direction of the elements is horizontal and `centered` typesetting, can it be set as the default `left-to-right` typesetting.
2. How to set up **multiple MiniMasonry** instances that need to be used in the page.
3. Have you ever set the default number of `columns` as a parameter to replace `baseWidth`?

**Comment by Spope** [comment]
Hi, thanks for the suggestions, sorry for the delay, I've been busy since this happend to my VPS provider: [oups](https://korben.info/app/uploads/2021/03/incendie-scaled.jpg).
(yeah backup to)

1. Good idea, I'll look if I can do that, but this will no be the default behaviour to avoid BC. Maybe a parameter with ltr, center, rtl, we'll see.
2. Please take a look to the [codepen](https://codepen.io/Spope/pen/WNwrpyd) provided in the documentation.
3. Nope, this library started with this specific need I had, the behaviour you're describing is provided by plenty of other masonry library. I try to keep the scope of this one simple.

**Comment by awnawnawn** [comment]
It's okay, thank you for taking the time to reply.
For the second question, I also wrote a [codepen](https://codepen.io/abawn/pen/YzpMeGB). Could you please help to see if it is better to implement **multiple MiniMasonry** instances? 
Do you have a better way?

**Comment by Spope** [comment]
I think this PR will make yout life easier : https://github.com/Spope/MiniMasonry.js/pull/7 (not published yet, doing it a soon as I can).

**Comment by awnawnawn** [comment]
Is the author still maintaining this plugin?

**Comment by Spope** [comment]
I am adding two new parameters, direction ("ltr" and "rtl") and a "wedge" boolean. Direction is obvious, wedge to true will start displaying columns from left or right according to direction.
